name: Build Android APK

env:
  # The name of the main project module
  main_project_module: app

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Set up Gradle cache
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Build APK with Gradle
      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      # Upload APK as GitHub Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/*.apk
